# Generated by Django 4.0.3 on 2022-03-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='category name')),
                ('slug', models.SlugField(max_length=128, verbose_name='category safe url')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
