# Generated by Django 4.0.3 on 2022-04-17 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productinventoryattributevalue',
            unique_together={('product_inventory', 'product_attribute_value')},
        ),
    ]
